# ----------------------------------------------------------------------------------------------------
# BETA: (Untested!) Pipeline to scan/build an app upon Pull Request and do a PR review summary with an LLM
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
# FYI -> Set a required branch policy to run this on every check to main 
# ----------------------------------------------------------------------------------------------------
trigger:
  - none
pr:
- main

# ----------------------------------------------------------------------------------------------------
variables:
  - group: Dadabase.Demo
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- template: stages/scan-code-stages.yml
  parameters:
    runMSDevSecOpsScan: true
    runGHASScan: false

- template: stages/webapp-build-stages.yml
  parameters:
    runUnitTests: true

# Include an LLM PR Review with LLM stage
- template: stages/pr-review-llm-stages.yml
