# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to Run Security Scan
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
 - none

schedules:
- cron: '0 2 * * 3'
  displayName: Scan Every Wednesday
  branches:
    include:
    - main

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: true
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runSBOM
    displayName: Generate Software Bill of Materials (SBOM)
    type: boolean
    default: true

# ----------------------------------------------------------------------------------------------------
variables:
  - group: Dadabase.Demo
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- template: stages/scan-code-stages.yml
  parameters:
    runGHASScan: ${{ parameters.runGHASScan }}
    runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
    runSBOM: ${{ parameters.runSBOM }}
