# ----------------------------------------------------------------------------------------------------
# Template to deploy a SQL Dacpac File to a SQL Database
# ----------------------------------------------------------------------------------------------------
# Unless you are using a local user/password, you must find the service principal name that is running
# your pipeline and execute these commands in the Azure SQL Database to grant access:
#   CREATE USER yourSP FROM EXTERNAL PROVIDER
#   ALTER ROLE db_owner ADD MEMBER yourSP
# And your ID that runs the app will need these permissions:
#   CREATE USER [dadabase-app-id] FROM EXTERNAL PROVIDER;
#   GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[Dad] TO [dadabase-app-id];
#   GRANT EXECUTE ON SCHEMA::[Dad] TO [dadabase-app-id];
# See also https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-configure?view=azuresql&tabs=azure-cli#provision-microsoft-entra-admin-sql-database
# ----------------------------------------------------------------------------------------------------
# If you don't you might see this error:
#   ##[error]Unable to connect to target server 'xxxdacpacdemo.database.windows.net'. Please verify the connection information such as the server name, login credentials, and firewall rules for the target server.
#   ##[error]Login failed for user '<token-identified principal>'.
#   ##[error]The Azure SQL DACPAC task failed. SqlPackage.exe exited with code 1.Check out how to troubleshoot failures at https://aka.ms/sqlazuredeployreadme#troubleshooting-
# ----------------------------------------------------------------------------------------------------
# Script to display role members:
#   SELECT DP1.name AS DatabaseRoleName, isnull (DP2.name, 'No members') AS DatabaseUserName   
#   FROM sys.database_role_members AS DRM  
#   RIGHT OUTER JOIN sys.database_principals AS DP1 ON DRM.role_principal_id = DP1.principal_id  
#   LEFT OUTER JOIN sys.database_principals AS DP2 ON DRM.member_principal_id = DP2.principal_id  
#   WHERE DP1.type = 'R' and DP1.name = 'db_owner'
#   ORDER BY DP1.name
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: environmentName
  default:  'DEV'
- name: artifactName
  default: 'dacpac'
- name: appProjectName
  default: ''
- name: loginAccountType
  default: 'SVC_PRINCIPAL'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: Deploy${{ parameters.environmentName }}Schema
  displayName: Initialize ${{ parameters.environmentName }} Deploy Schema
  environment: ${{ parameters.environmentName }}

- job: DeployDB${{ parameters.environmentName }}Schema
  displayName: Deploy ${{ parameters.environmentName }} Schema
  variables:
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: sqlServerName
      value: $(SQL_SERVER_NAME_PREFIX)$(INSTANCE_NUMBER)sql${{ lower(parameters.environmentName) }}
    - name: fqdnServerName
      value: $(sqlServerName).database.windows.net

    # Bring in environment common variable file
    - template: ../vars/var-service-connections.yml
    - template: ../vars/var-common.yml
    
    # Bring in environment specific variable files
    - ${{ if eq(lower(parameters.environmentName), 'dev') }}:
      - template: ../vars/var-dev.yml
    - ${{ if eq(lower(parameters.environmentName), 'qa') }}:
      - template: ../vars/var-qa.yml
    - ${{ if eq(lower(parameters.environmentName), 'prod') }}:
      - template: ../vars/var-prod.yml

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '${{ parameters.artifactName }}'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CmdLine@2
    displayName: 'Display Variables and Files'
    inputs:
      script: |
        echo "serviceConnectionDEV=$(serviceConnectionDEV)"
        echo "serviceConnectionQA=$(serviceConnectionQA)"
        echo "serviceConnectionPROD=$(serviceConnectionPROD)"
        echo "environmentNameUpper=$(environmentNameUpper)"
        echo "environmentNameLower=$(environmentNameLower)"
        echo "artifactName=${{ parameters.artifactName }}"
        echo "sqlServerNamePrefix=$(SQL_SERVER_NAME_PREFIX)"
        echo "sqlServerName=$(sqlServerName)"
        echo "fqdnServerName=$(fqdnServerName)"
        echo "sqlDatabaseName=$(SQL_DATABASE_NAME)"
        echo "sqlAdminUser=$(SQLADMIN_LOGIN_USERID)"
        echo "sqlAdminPassword=$(SQL_DATABASE_PASSWORD)"
        echo "DacpacFileLocation=$$(System.ArtifactsDirectory)\${{ parameters.artifactName }}\*.dacpac"
        echo "Directory of Artifacts Directory: $(System.ArtifactsDirectory)"
        dir $(System.ArtifactsDirectory) /s
    continueOnError: true
  
  # in order to use multiple dynamic service connections, you can't just use a variable.
  # they need to be defined and available at YML pre-compile time, so use this technique.
  # this switch allows you to dynamically select a 'hard-coded' service connection
  - ${{ if eq(variables.environmentNameUpper, 'DEV') }}:
    - template: ../steps/dacpac-deploy-steps.yml
      parameters:
        serviceConnectionName: $(serviceConnectionDEV)
        loginAccountType: ${{ parameters.loginAccountType }}
        artifactName: ${{ parameters.artifactName }}
        appProjectName: ${{ parameters.appProjectName }}
        fqdnServerName: $(fqdnServerName)
        sqlDatabaseName: $(SQL_DATABASE_NAME)
        sqlAdminUser: $(SQLADMIN_LOGIN_USERID)
        sqlAdminPassword: $(SQL_DATABASE_PASSWORD)
  - ${{ if eq(variables.environmentNameUpper, 'QA') }}:
    - template: ../steps/dacpac-deploy-steps.yml
      parameters:
        serviceConnectionName: $(serviceConnectionQA)
        loginAccountType: ${{ parameters.loginAccountType }}
        artifactName: ${{ parameters.artifactName }}
        appProjectName: ${{ parameters.appProjectName }}
        fqdnServerName: $(fqdnServerName)
        sqlDatabaseName: $(SQL_DATABASE_NAME)
        sqlAdminUser: $(SQLADMIN_LOGIN_USERID)
        sqlAdminPassword: $(SQL_DATABASE_PASSWORD)
  - ${{ if eq(variables.environmentNameUpper, 'PROD') }}:
    - template: ../steps/dacpac-deploy-steps.yml
      parameters:
        serviceConnectionName: $(serviceConnectionPROD)
        loginAccountType: ${{ parameters.loginAccountType }}
        artifactName: ${{ parameters.artifactName }}
        appProjectName: ${{ parameters.appProjectName }}
        fqdnServerName: $(fqdnServerName)
        sqlDatabaseName: $(SQL_DATABASE_NAME)
        sqlAdminUser: $(SQLADMIN_LOGIN_USERID)
        sqlAdminPassword: $(SQL_DATABASE_PASSWORD)
